### ISSUE TITLE
Kademlia Add Seen Node

### ISSUE THREAD

**Issue by naddah-5** [D7024E/D7024E#60]
Add functionality for kademlia to attempt to add all nodes it sees. If it already exists in a bucket the attempt is immediately terminated, if it is not in the appropriate bucket continue. Check if the node that has been in the bucket the longest without being seen again is still alive, via ping, if it is alive it should be moved to most recently seen and the attempt to add the new node terminates. However, if it does not respond we should discard it and add the new node as the most recently seen.

Can likely be implemented by modifying AddContact.

**Comment by Denne213** [comment]
Done add in #126. Remove and ping left
